### ISSUE TITLE
The source code of JouleUWP seems not complete

### ISSUE THREAD

**Issue by mediaexplorer74** [mitchcapper/JouleUWP#10]
Hi!
I researched your project. The source code of JouleUWP seems not complete.
Do you have decompiled Android apk?... Classes, etc.

**Comment by mitchcapper** [comment]
chefsteps was working on a public API however it has been quite some time so I am not sure if it will still be released.   Over BT joule used protocol buffers although the web socket/web requests for the cloud might be an easier path.

**Comment by mediaexplorer74** [comment]
> chefsteps was working on a public API however it has been quite some time so I am not sure if it will still be released. Over BT joule used protocol buffers although the web socket/web requests for the cloud might be an easier path.

Ok. Thanx for quick reply. I forked your great project. 
Wish once day you continue your RnD on Joule ;)
- me
