### ISSUE TITLE
Protocol Buffers

### ISSUE THREAD

**Issue by Yitzchok** [mitchcapper/JouleUWP#9]
It looks like the binary data is serialized using Protocal Buffers https://developers.google.com/protocol-buffers/

Not jsonp or maybe you mean bson

**Comment by mitchcapper** [comment]
Thanks! I did mean bjson.  I actually was just looking at their protocol buffer prototype classes as it contains the values for the different message types.

I will work to update the documentation soon.

**Comment by mitchcapper** [comment]
Thanks I have updated the documentation, I am not sure if you had a chance to attempt to decode either the bluetooth or web socket communication to see if that works, but once I am able to get infront of a Joule again I will give it a shot.

**Comment by Yitzchok** [comment]
I didn't yet get my Joule device.

**Comment by mitchcapper** [comment]
Extra thanks for looking into it ahead of getting a Joule. Will let you know what I find, sadly they are using v2 and native c# class generation isn't until v3. There is an alternate .net c# generator I plan to try however.  I could convert their files to v3 pretty easily, but im not sure the interop between the versions will play nicely.

**Comment by Yitzchok** [comment]
John Skeet has a protobuf dot net library for v2 https://github.com/jskeet/protobuf-csharp-port.
